name: Deployment

on:
  push:
    branches: 
      - main
  workflow_dispatch:



jobs:
  test:
    name: "Python VENV Test"
    runs-on: ubuntu-latest
    env:
      TESTING: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: "Setup Python Environment"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: "Setup Python Virtual Environment"
        run: python -m venv py3

      - name: "Installing Dependencies"
        run: |
             source py3/bin/activate
             pip install -r requirements.txt
      
      - name: "Run Tests"
        run: ./run_test.sh

      - name: "Send Notification to Discord if test fails"
        if: failure()
        run: |
             curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
             -d "content=Tests Failed"


  deploy:
    # Only allow deployment when the test passes
    needs: test
    name: "Deploy to VPS"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
            chmod 600 ~/.ssh/deploy-key.pem
            cat >> ~/.ssh/config <<END
            Host my-vps
              HostName $SSH_IP
              User $SSH_USER
              IdentityFile ~/.ssh/deploy-key.pem
              StrictHostKeyChecking no
            END

        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_IP: ${{ secrets.SSH_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Site
        run: ssh my-vps "~/redeploy-site"

      - name: "Print Container Status"
        run: ssh my-vps "cd ~/portfolio && docker compose ps"
      
      - name: "Send Discord Notification on Deployment Success"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -s -X POST "$DISCORD_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d '{"content":"Deployment Successful"}'

      - name: "Send Discord Notification on Deployment Failure"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: failure()
        run: |
             curl -s -X POST "$DISCORD_WEBHOOK" \
             -H "Content-Type: application/json" \
             -d '{"content": "Deployment Failed"}'


